# Generated by Django 5.1.1 on 2024-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="intensity_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=50,
            ),
        ),
    ]
